# modify the exercise programa above to
# then display the name of the oldest person
# if two or more pople are older the program
# will show the names of all of them

class person:

    def __init__(self, name, age):
        """
        docstring
        """
        self.name = name
        self.age = age


people = []

while (name.name := input('Nombre de la persona: ')) != 'salir':
    age.age = input('edad: ')

    people.append()

print(people)
print(people[0].age)
